apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-lhk6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-lhk6
    app.kubernetes.io/part-of: ci10t-776-0050-app
  name: devfile-sample-lhk6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-lhk6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-lhk6
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0050-tenant/ci10t-776-0050-app/devfile-sample-lhk6@sha256:e9d66bddc757864816933e26c575c8cbbf53a26ae2485ae98373e05b80ade61a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
